@startuml
Actor Passenger

activate ReservationSystemFacadeImpl
Passenger -> ReservationSystemFacadeImpl: findAirlinesByAirportCode(String airportCode)

activate ReservationSystemFacadeImpl
ReservationSystemFacadeImpl -> ReservationSystemFacadeImpl: findAirportByAirportCode(airportCode)
deactivate ReservationSystemFacadeImpl

activate Airport
ReservationSystemFacadeImpl -> Airport: getDepartureFlights()
Airport --> ReservationSystemFacadeImpl: List<FlightNumber> flightNumbers
deactivate Airport

activate FlightNumber
ReservationSystemFacadeImpl -> FlightNumber: getAirlineOwn()
FlightNumber --> ReservationSystemFacadeImpl: Airline airline
deactivate FlightNumber

ReservationSystemFacadeImpl --> Passenger: List<Airline> airlines
deactivate ReservationSystemFacadeImpl
@enduml