@startuml ViewFlights
Actor Passenger


Passenger -> ReservationSystemFacadeImpl : findFlightsFromTo(departure:string, arrival:string, date Date)
activate ReservationSystemFacadeImpl
ReservationSystemFacadeImpl -> StorageHandler : flights
activate StorageHandler
deactivate
ReservationSystemFacadeImpl -> Flight: getFlightNumber()
activate Flight
Flight -> FlightNumber: getArrivalAirport()
activate FlightNumber
FlightNumber -> Airport: getName()
activate Airport
deactivate
deactivate
Flight -> FlightNumber: getDepartureAirport(Date)
activate FlightNumber
FlightNumber -> Airport: getName()
activate Airport
deactivate
deactivate
deactivate
deactivate


@enduml