@startuml ViewFlights
Actor Passenger


Passenger -> SystemHelper : getFlights(Dapart, Arrival, Date)
activate SystemHelper
SystemHelper -> FlightInstance : getAllDeparturesOnDate(Date)
activate FlightInstance
FlightInstance -> Address : getAirportName
activate Address
deactivate
deactivate

SystemHelper -> FlightInstance : getAllArrivalOnDate(Date)
activate FlightInstance
FlightInstance -> Address : getAirportName
activate Address
deactivate

deactivate
SystemHelper -> SystemHelper : compareAndGet(Depart, Arrival, allDeparts, allArrivals)
activate SystemHelper
deactivate
deactivate


@enduml