@startuml ViewReservations
'Actor Passenger


start -> ReservationSystemFacadeImpl : findReservationsByPassengerId()
activate ReservationSystemFacadeImpl
ReservationSystemFacadeImpl -> StorageHandler: getPassengers()
activate StorageHandler
deactivate
ReservationSystemFacadeImpl -> Passenger: getUuid()
activate Passenger
deactivate
deactivate

@enduml