@startuml

-> PassengerController: MakeAReservation(flights: List<Flight>)
activate PassengerController
PassengerController -> Reservation : Initialize
activate Reservation
deactivate Reservation

PassengerController -> Ticket: Create a ticket
activate Ticket
deactivate Ticket

PassengerController -> Ticket: get Reservation code
activate Ticket

@enduml
