@startuml cancel_reservation

-> ReservationSystemFacadeImpl: cancelReservation(reservationCode : String) 
activate ReservationSystemFacadeImpl

ReservationSystemFacadeImpl -> StorageHandler : removeTickets(reservationCode : String)
activate StorageHandler
ReservationSystemFacadeImpl -> StorageHandler : removeReservation(reservationCode : String)
deactivate StorageHandler

deactivate ReservationSystemFacadeImpl

@enduml
