@startuml agent_reservation

-> ReservationSystemFacadeImpl: createReservation(agent:Agent, passenger:Passenger, flights: List<Flight>)
activate ReservationSystemFacadeImpl
ReservationSystemFacadeImpl -> Reservation : Initialize with Agent Uuid
activate Reservation

ReservationSystemFacadeImpl -> Reservation: getReservationCode()

ReservationSystemFacadeImpl -> Ticket: Initialize
activate Ticket
deactivate Ticket

ReservationSystemFacadeImpl -> Reservation: addTicket()
deactivate Reservation

ReservationSystemFacadeImpl -> Passenger: addReservation()
activate Passenger
deactivate Passenger

ReservationSystemFacadeImpl -> StorageHandler: addReservation
activate StorageHandler
ReservationSystemFacadeImpl -> StorageHandler: setTickets
deactivate StorageHandler

@enduml
