@startuml cancel_reservation

-> ReservationSystemFacadeImpl: confirmReservation(reservationCode : String) 
activate ReservationSystemFacadeImpl

ReservationSystemFacadeImpl -> StorageHandler : getReservationByCode(reservationCode : String)
activate StorageHandler
deactivate StorageHandler

ReservationSystemFacadeImpl -> StorageHandler : getReservationByCode(reservationCode : String)
activate StorageHandler
deactivate StorageHandler

ReservationSystemFacadeImpl -> Reservation : confirm()
activate Reservation
deactivate Reservation

ReservationSystemFacadeImpl -> StorageHandler : updateReservation(reservation : Reservation)
activate StorageHandler
deactivate StorageHandler

deactivate ReservationSystemFacadeImpl

@enduml
